// Every machine-readable `code` an error answer can carry, with what it means. Published in the OpenAPI spec so a client
// can branch on `code` (the human `detail` text may be reworded; codes are stable). The test errorCodesList.test.ts fails
// if source uses a code that is not listed here.
export const ERROR_CODES: Record<string, string> = {
  // generic, from the status when nothing more specific applies
  bad_request: 'The request was not valid.',
  unauthorized: 'Authentication is required or failed.',
  forbidden: 'Not allowed.',
  not_found: 'No such resource or URL.',
  method_not_allowed: 'That method is not allowed on this URL.',
  conflict: 'The request conflicts with the current state.',
  precondition_failed: 'The If-Match precondition did not hold.',
  draft_version_conflict: 'The draft was saved somewhere else since you loaded it; reload before saving.',
  payload_too_large: 'The request body is over the size limit.',
  unsupported_media_type: 'Send JSON (Content-Type: application/json).',
  unprocessable: 'The request could not be processed.',
  rate_limited: 'Too many requests. See the Retry-After header.',
  internal_error: 'Something went wrong on our side.',
  bad_gateway: 'A service behind this API answered badly.',
  service_unavailable: 'A service behind this API is unavailable.',
  gateway_timeout: 'A service behind this API took too long.',
  client_error: 'The request was refused.',
  server_error: 'Something went wrong on our side.',
  // requests
  validation_error: 'A field is missing or invalid; detail says which.',
  invalid_json: 'The body is not valid JSON.',
  invalid_characters: 'A text value contains the NUL character (U+0000), which cannot be stored.',
  invalid_request: 'The request was rejected by the service behind this API.',
  invalid_signature: 'The request is not signed correctly by the sender.',
  invalid_id: 'An identifier in the address is not in the expected format.',
  client_closed: 'The caller closed the connection before the answer was ready (never seen by the caller).',
  idempotency_conflict: 'The Idempotency-Key was reused with a different request, or the first request is still running.',
  // sign-in and sessions
  authentication_required: 'No session or API key was sent.',
  session_invalid: 'The session is unknown or has expired.',
  session_not_found: 'That session does not exist or is not yours.',
  invalid_credentials: 'Wrong email or password.',
  current_password_incorrect: 'The current password given is not correct.',
  signin_locked: 'Too many failed sign-ins; try again after the Retry-After time.',
  email_not_confirmed: 'The email address has not been confirmed yet.',
  email_in_use: 'An account with that email already exists.',
  password_reset_required: 'This account must reset its password before signing in.',
  password_too_short: 'The password is too short.',
  password_too_long: 'The password is too long.',
  password_missing_uppercase: 'The password needs an uppercase letter.',
  password_missing_lowercase: 'The password needs a lowercase letter.',
  password_missing_number: 'The password needs a number.',
  password_missing_symbol: 'The password needs a symbol.',
  first_name_required: 'A first name is required.',
  last_name_required: 'A last name is required.',
  invalid_or_expired_token: 'The emailed link is not valid or has expired.',
  origin_not_allowed: 'Requests from this website origin are not allowed.',
  cross_site_blocked: 'Cross-site requests are not allowed.',
  // API keys
  api_key_required: 'An x-api-key header is required.',
  invalid_api_key: 'The API key is unknown or has been revoked.',
  api_key_service_not_enabled: 'The key is not enabled for this API.',
  market_analysis_daily_cap: 'The key has used its market analyses for today.',
  api_key_scope_missing: 'The key does not include the part of the Desk API this endpoint belongs to.',
  api_key_endpoint_not_allowed: 'A key cannot call this endpoint.',
  api_key_limit_reached: 'The account already has the maximum number of active keys.',
  api_key_service_unavailable: 'One of the chosen APIs is not available for new keys right now.',
  api_key_not_found: 'That key does not exist or is not yours.',
  api_key_already_revoked: 'That key was already revoked.',
  admin_required: 'Administrator access is required.',
  admin_recent_signin_required: 'Administrator routes need a sign-in from the last 24 hours; sign in again.',
  admin_key_ip_not_allowed: 'The administrator key is not accepted from this address.',
  account_suspended: 'This account has been suspended.',
  api_key_expired: 'The API key is past its expiry date.',
  api_key_idle: 'The API key was not used for six months and was switched off.',
  api_key_suspended: 'This API key is suspended (switched off without being revoked).',
  admin_not_available_for_keys: 'Administrator routes cannot be used with an API key.',
  // businesses and setup
  business_not_found: 'That business does not exist or you are not a member.',
  draft_not_found: 'That setup draft does not exist.',
  draft_limit_reached: 'Too many unfinished setup drafts; finish or delete one.',
  draft_too_large: 'The setup draft is over the size limit.',
  draft_unreadable: 'The saved draft could not be read.',
  business_name_required: 'A business name is required to finish setup.',
  business_name_too_long: 'The business name is over 200 characters.',
  industry_too_long: 'The industry is over 100 characters.',
  insufficient_role: 'Only owners and admins can do that.',
  owner_role_required: 'Only an owner can do that.',
  last_owner: 'A business must keep at least one owner.',
  already_member: 'That person is already a member.',
  invite_not_found: 'That invitation does not exist.',
  invite_limit_reached: 'The business has too many invitations waiting.',
  membership_not_found: 'That membership or invitation does not exist.',
  // things behind the API
  unknown_endpoint: 'That endpoint does not exist on this API.',
  api_unavailable: 'The API is temporarily unavailable for this key.',
  upstream_unavailable: 'A service behind this API is temporarily unavailable; try again shortly.',
  upstream_unreachable: 'A service behind this API could not be reached.',
  upstream_rejected: 'A service behind this API refused the request.',
  upstream_response_too_large: 'A service behind this API answered with more data than allowed.',
  upstream_not_configured: 'That service is not set up.',
  upstream_provisioning_failed: 'Access to one of the chosen APIs could not be set up; nothing was created.',
  service_busy: 'The API is busy; try again in a moment.',
  too_many_in_flight: 'You already have the maximum number of requests running.',
  structure_not_found: 'That business structure does not exist.',
  // admin table browser
  table_not_found: 'That table does not exist.',
  row_not_found: 'That row does not exist.',
  delete_disabled: 'Deleting is not allowed on that table.',
};
