version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      devDependencies:
        dependency-type: development
      dependencies:
        dependency-type: production
