-- Adds resumable-shard tracking to market_reference_batch_runs.
--
-- Why: the original batch job (reference-distribution-batch.ts before this
-- migration) fetched and stored the ENTIRE national dataset — all metrics x
-- all jurisdiction levels x all states/counties/places — inside one single
-- Worker invocation. In production that hit Cloudflare Workers' hard
-- per-invocation subrequest ceiling ("Too many subrequests by single Worker
-- invocation") partway through, most of the cost coming from D1 upsert
-- batches scaling with row count (~30,000 Census places alone). The run
-- silently truncated: place/county levels never completed for any metric,
-- and the five trend metrics (last in fetch order) never got breakpoints at
-- all.
--
-- The fix splits the job into ~230 small "shards" (one state, one metric,
-- or a final breakpoints pass — see buildShardPlan() in
-- reference-distribution-batch.ts) processed a few at a time by a new
-- frequent cron tick (advanceReferenceDistributionBatch), instead of all at
-- once by the daily cron. These columns let a run persist exactly where it
-- left off between invocations:
--   * shard_plan       — JSON array of shard keys, fixed for the run's
--                         lifetime once generated by buildShardPlan().
--   * next_shard_index — cursor into shard_plan; advanced (and persisted)
--                         after each shard, so a crash mid-tick only
--                         re-does the last few shards (upserts are
--                         idempotent via ON CONFLICT), never restarts from
--                         zero.
--   * total_shards     — shard_plan.length, cached for cheap progress
--                         reporting without re-parsing the JSON.

ALTER TABLE market_reference_batch_runs ADD COLUMN shard_plan TEXT NOT NULL DEFAULT '[]';
ALTER TABLE market_reference_batch_runs ADD COLUMN next_shard_index INTEGER NOT NULL DEFAULT 0;
ALTER TABLE market_reference_batch_runs ADD COLUMN total_shards INTEGER NOT NULL DEFAULT 0;
