export type BusinessStructureCategory =
  | 'legal_entity'
  | 'tax_election'
  | 'special_designation'
  | 'regulatory_status'
  | 'international_entity';

export type BusinessStructureFamily =
  | 'sole_proprietorship'
  | 'partnership'
  | 'llc'
  | 'corporation'
  | 'nonprofit'
  | 'cooperative'
  | 'trust'
  | 'joint_venture'
  | 'government'
  | 'international';

export type BusinessStructure = {
  slug: string;
  name: string;
  category: BusinessStructureCategory;
  family: BusinessStructureFamily;
  aliases: string[];
  summary: string;
  ownership: string;
  liability: string;
  taxation: string;
  management: string;
  formation: string;
  bestFor: string[];
  cautions: string[];
  variants?: string[];
  taxElectionOptions?: string[];
  jurisdictionNotes?: string[];
  countries?: string[];
  relatedStructures?: string[];
};

export type BusinessStructureRecommendationInput = {
  ownerCount?: number;
  nonprofit?: boolean;
  wantsLiabilityProtection?: boolean;
  wantsStock?: boolean;
  ventureBacked?: boolean;
  licensedProfessional?: boolean;
  realEstateOrHoldings?: boolean;
  charitablePurpose?: boolean;
  cooperativeOwnership?: boolean;
  country?: string;
  stateCode?: string;
};

const commonTaxElections = [
  'disregarded_entity',
  'partnership_taxation',
  'c_corporation_taxation',
  's_corporation_taxation',
];

export const BUSINESS_STRUCTURES: BusinessStructure[] = [
  {
    slug: 'sole_proprietorship',
    name: 'Sole Proprietorship',
    category: 'legal_entity',
    family: 'sole_proprietorship',
    aliases: ['sole prop', 'sole trader', 'individual proprietorship'],
    summary:
      'An unincorporated business owned by one individual, usually with no separate legal entity.',
    ownership: 'One owner.',
    liability: 'Unlimited personal liability.',
    taxation: 'Business income is generally reported directly by the owner.',
    management: 'Owner manages directly.',
    formation:
      'Often no state entity filing, though licenses, DBAs, permits, and tax registrations may still be required.',
    bestFor: [
      'Very small owner-operated businesses',
      'Low-risk services',
      'Testing a business idea',
    ],
    cautions: [
      'No liability shield',
      'Harder to raise outside capital',
      'Business continuity depends on the owner',
    ],
    taxElectionOptions: ['sole_proprietor_taxation'],
    relatedStructures: ['single_member_llc'],
  },
  {
    slug: 'general_partnership',
    name: 'General Partnership',
    category: 'legal_entity',
    family: 'partnership',
    aliases: ['GP', 'ordinary partnership'],
    summary: 'An unincorporated business with two or more owners carrying on as co-owners.',
    ownership: 'Two or more partners.',
    liability: 'Partners generally have unlimited personal liability for partnership obligations.',
    taxation: 'Pass-through partnership taxation.',
    management: 'Partners manage unless an agreement says otherwise.',
    formation:
      'Can arise by conduct; may require DBA, tax, license, or partnership filings depending on jurisdiction.',
    bestFor: ['Simple co-owned businesses', 'Short-term low-risk ventures'],
    cautions: [
      'Each partner can bind the partnership',
      'Personal assets are at risk',
      'Needs a strong partnership agreement',
    ],
    taxElectionOptions: ['partnership_taxation'],
    relatedStructures: [
      'limited_partnership',
      'limited_liability_partnership',
      'limited_liability_company',
    ],
  },
  {
    slug: 'limited_partnership',
    name: 'Limited Partnership',
    category: 'legal_entity',
    family: 'partnership',
    aliases: ['LP'],
    summary: 'A partnership with at least one general partner and one limited partner.',
    ownership: 'General partners and limited partners.',
    liability:
      'General partners usually have unlimited liability; limited partners usually have liability limited to investment.',
    taxation: 'Pass-through partnership taxation by default.',
    management: 'General partner manages; limited partners are usually passive investors.',
    formation: 'Requires state filing in most U.S. jurisdictions.',
    bestFor: ['Real estate projects', 'Private funds', 'Passive investor structures'],
    cautions: [
      'General partner liability must be managed',
      'Limited partner control can affect liability protection',
    ],
    taxElectionOptions: ['partnership_taxation'],
    relatedStructures: ['limited_liability_limited_partnership', 'limited_liability_company'],
  },
  {
    slug: 'limited_liability_partnership',
    name: 'Limited Liability Partnership',
    category: 'legal_entity',
    family: 'partnership',
    aliases: ['LLP', 'registered limited liability partnership'],
    summary:
      'A partnership form providing liability protection, commonly used by professional firms.',
    ownership: 'Two or more partners.',
    liability:
      'Often shields partners from obligations or malpractice of other partners, subject to state rules.',
    taxation: 'Pass-through partnership taxation by default.',
    management: 'Partners manage under a partnership agreement.',
    formation: 'Requires state registration; availability and professional restrictions vary.',
    bestFor: [
      'Law firms',
      'Accounting firms',
      'Architecture firms',
      'Professional services partnerships',
    ],
    cautions: [
      'Not available for every business type in every state',
      'Does not eliminate personal malpractice liability',
    ],
    taxElectionOptions: ['partnership_taxation'],
    jurisdictionNotes: ['Often profession-specific or registration-specific under state law.'],
    relatedStructures: ['professional_limited_liability_company', 'professional_corporation'],
  },
  {
    slug: 'limited_liability_limited_partnership',
    name: 'Limited Liability Limited Partnership',
    category: 'legal_entity',
    family: 'partnership',
    aliases: ['LLLP'],
    summary:
      'A limited partnership variant that can provide liability protection to general partners.',
    ownership: 'General partners and limited partners.',
    liability: 'Limited liability may extend to general partners, depending on jurisdiction.',
    taxation: 'Pass-through partnership taxation by default.',
    management: 'General partner manages.',
    formation: 'Requires state filing where recognized.',
    bestFor: [
      'Real estate holdings',
      'Investment partnerships',
      'Family limited partnership planning',
    ],
    cautions: ['Not recognized in all states', 'State-by-state rules matter heavily'],
    taxElectionOptions: ['partnership_taxation'],
    relatedStructures: ['limited_partnership'],
  },
  {
    slug: 'limited_liability_company',
    name: 'Limited Liability Company',
    category: 'legal_entity',
    family: 'llc',
    aliases: ['LLC', 'LC'],
    summary: 'A flexible legal entity with liability protection and broad tax election options.',
    ownership: 'Members; can be one or many.',
    liability: 'Members generally receive limited liability.',
    taxation:
      'Default tax treatment depends on owner count; may elect corporate or S corporation taxation if eligible.',
    management: 'Member-managed or manager-managed.',
    formation: 'Requires state articles/certificate of organization and ongoing state compliance.',
    bestFor: [
      'Small businesses wanting liability protection',
      'Flexible ownership',
      'Real estate and holding companies',
    ],
    cautions: [
      'Venture investors may prefer corporations',
      'State fees and franchise taxes vary',
      'Operating agreement is important',
    ],
    variants: [
      'single_member_llc',
      'multi_member_llc',
      'series_llc',
      'professional_limited_liability_company',
      'low_profit_limited_liability_company',
      'restricted_limited_liability_company',
      'public_benefit_llc',
    ],
    taxElectionOptions: commonTaxElections,
    relatedStructures: ['corporation', 'limited_partnership'],
  },
  {
    slug: 'single_member_llc',
    name: 'Single-Member LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['SMLLC', 'single member limited liability company'],
    summary: 'An LLC with one member.',
    ownership: 'One member.',
    liability: 'Member generally receives limited liability.',
    taxation: 'Disregarded entity by default for federal tax unless corporate taxation is elected.',
    management: 'Usually member-managed, but can be manager-managed.',
    formation: 'Formed as an LLC under state law.',
    bestFor: [
      'Solo founders wanting liability protection',
      'Holding companies',
      'Real estate owners',
    ],
    cautions: ['Separate finances and records are important to preserve liability protection'],
    taxElectionOptions: ['disregarded_entity', 'c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['limited_liability_company', 'sole_proprietorship'],
  },
  {
    slug: 'multi_member_llc',
    name: 'Multi-Member LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['MMLLC', 'multi member limited liability company'],
    summary: 'An LLC with two or more members.',
    ownership: 'Two or more members.',
    liability: 'Members generally receive limited liability.',
    taxation: 'Partnership taxation by default unless corporate taxation is elected.',
    management: 'Member-managed or manager-managed.',
    formation: 'Formed as an LLC under state law.',
    bestFor: ['Co-founders', 'Family businesses', 'Flexible profit allocations'],
    cautions: ['Needs a strong operating agreement'],
    taxElectionOptions: [
      'partnership_taxation',
      'c_corporation_taxation',
      's_corporation_taxation',
    ],
    relatedStructures: ['limited_liability_company', 'general_partnership'],
  },
  {
    slug: 'series_llc',
    name: 'Series LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['SLLC'],
    summary: 'An LLC that can create separate internal series with distinct assets or operations.',
    ownership: 'Master LLC members; series may have associated members or assets.',
    liability: 'Series liability separation depends on state law and proper records.',
    taxation: 'Tax treatment varies by series and elections.',
    management: 'Managed under master and series governing documents.',
    formation: 'Available only in some jurisdictions.',
    bestFor: ['Multiple real estate properties', 'Multiple brands', 'Investment holdings'],
    cautions: [
      'Interstate recognition can be uncertain',
      'Requires careful accounting and records',
    ],
    taxElectionOptions: commonTaxElections,
    jurisdictionNotes: ['Recognized only in selected states.'],
    relatedStructures: ['limited_liability_company'],
  },
  {
    slug: 'professional_limited_liability_company',
    name: 'Professional LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['PLLC', 'professional limited liability company'],
    summary: 'An LLC variant for licensed professional services.',
    ownership: 'Often restricted to licensed professionals.',
    liability:
      'Limited liability for business obligations, but not personal professional malpractice.',
    taxation: 'Usually LLC tax options if otherwise eligible.',
    management: 'Member-managed or manager-managed, subject to licensing rules.',
    formation: 'May require licensing board approval or professional purpose language.',
    bestFor: ['Doctors', 'Dentists', 'Lawyers', 'Architects', 'Accountants', 'Engineers'],
    cautions: ['State licensing rules vary', 'Some states require PC/PA instead'],
    taxElectionOptions: commonTaxElections,
    relatedStructures: ['professional_corporation', 'limited_liability_partnership'],
  },
  {
    slug: 'low_profit_limited_liability_company',
    name: 'Low-Profit LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['L3C', 'low profit limited liability company'],
    summary: 'A mission-oriented LLC intended to bridge charitable and for-profit purposes.',
    ownership: 'Members.',
    liability: 'Members generally receive limited liability.',
    taxation: 'LLC tax options; no federal nonprofit status merely from being an L3C.',
    management: 'Member-managed or manager-managed.',
    formation: 'Recognized only in some jurisdictions.',
    bestFor: ['Mission-driven ventures', 'Program-related investment targets'],
    cautions: ['Not federally tax-exempt by default', 'Limited state recognition'],
    taxElectionOptions: commonTaxElections,
    relatedStructures: [
      'limited_liability_company',
      'benefit_corporation',
      'nonprofit_corporation',
    ],
  },
  {
    slug: 'restricted_limited_liability_company',
    name: 'Restricted LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['restricted LLC'],
    summary: 'A rare LLC variant with distribution restrictions under specific state law.',
    ownership: 'Members.',
    liability: 'Members generally receive limited liability.',
    taxation: 'LLC tax options.',
    management: 'Member-managed or manager-managed.',
    formation: 'State-specific and uncommon.',
    bestFor: ['Specialized estate or asset planning in states that recognize it'],
    cautions: ['Rare and not broadly recognized'],
    taxElectionOptions: commonTaxElections,
    relatedStructures: ['limited_liability_company'],
  },
  {
    slug: 'public_benefit_llc',
    name: 'Public Benefit LLC',
    category: 'special_designation',
    family: 'llc',
    aliases: ['benefit LLC', 'public benefit limited liability company'],
    summary: 'An LLC with a public benefit or mission obligation under state law where available.',
    ownership: 'Members.',
    liability: 'Members generally receive limited liability.',
    taxation: 'LLC tax options.',
    management: 'Member-managed or manager-managed with public benefit obligations.',
    formation: 'Available only in some jurisdictions.',
    bestFor: ['Mission-driven businesses wanting LLC flexibility'],
    cautions: ['State availability varies', 'Benefit reporting obligations may apply'],
    taxElectionOptions: commonTaxElections,
    relatedStructures: ['benefit_corporation', 'low_profit_limited_liability_company'],
  },
  {
    slug: 'corporation',
    name: 'Corporation',
    category: 'legal_entity',
    family: 'corporation',
    aliases: ['corp', 'inc', 'company limited by shares'],
    summary: 'A separate legal entity owned by shareholders.',
    ownership: 'Shareholders.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'C corporation taxation by default unless eligible S corporation election is made.',
    management: 'Board of directors and officers.',
    formation: 'Requires state articles/certificate of incorporation and corporate governance.',
    bestFor: [
      'Venture-backed startups',
      'Businesses issuing stock',
      'Companies planning many investors',
    ],
    cautions: ['More formal governance', 'Possible double taxation under C corporation treatment'],
    variants: [
      'c_corporation',
      's_corporation',
      'professional_corporation',
      'benefit_corporation',
      'close_corporation',
      'statutory_close_corporation',
      'public_corporation',
      'private_corporation',
    ],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['limited_liability_company'],
  },
  {
    slug: 'c_corporation',
    name: 'C Corporation',
    category: 'tax_election',
    family: 'corporation',
    aliases: ['C corp', 'C-corp'],
    summary: 'Federal corporate tax treatment, commonly associated with standard corporations.',
    ownership: 'Shareholders; no federal 100-shareholder S corporation limit.',
    liability:
      'Shareholders generally receive limited liability when used with a corporation or electing LLC.',
    taxation: 'Entity-level corporate tax; dividends may also be taxed to shareholders.',
    management: 'Usually board and officers for corporations.',
    formation: 'A tax classification, not always a separate legal entity type.',
    bestFor: [
      'Venture capital',
      'Qualified small business stock planning',
      'Multiple stock classes',
    ],
    cautions: ['Potential double taxation', 'Corporate formalities'],
    relatedStructures: ['corporation', 'limited_liability_company'],
  },
  {
    slug: 's_corporation',
    name: 'S Corporation',
    category: 'tax_election',
    family: 'corporation',
    aliases: ['S corp', 'S-corp', 'subchapter S corporation'],
    summary: 'A federal tax election available to qualifying corporations and some LLCs.',
    ownership:
      'Eligibility generally limited by shareholder count, owner type, residency, and one class of stock.',
    liability: 'Liability depends on the underlying legal entity.',
    taxation: 'Pass-through federal taxation under Subchapter S.',
    management: 'Depends on underlying entity.',
    formation: 'Tax election; not a standalone state legal entity.',
    bestFor: [
      'Profitable owner-operated businesses',
      'Businesses seeking pass-through taxation with payroll planning',
    ],
    cautions: [
      'Eligibility restrictions',
      'Reasonable compensation rules',
      'Not a legal entity by itself',
    ],
    relatedStructures: ['corporation', 'limited_liability_company'],
  },
  {
    slug: 'professional_corporation',
    name: 'Professional Corporation',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['PC', 'P.C.', 'professional service corporation'],
    summary: 'A corporation variant for licensed professional services.',
    ownership: 'Often restricted to licensed professionals.',
    liability: 'Limited liability for business obligations, but not personal malpractice.',
    taxation: 'Usually corporate taxation unless S election is available and made.',
    management: 'Board/officers, subject to professional ownership rules.',
    formation: 'May require licensing board approval.',
    bestFor: ['Medical practices', 'Law firms', 'Engineering firms', 'Accounting firms'],
    cautions: ['Professional licensing restrictions vary by state'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['professional_limited_liability_company', 'professional_association'],
  },
  {
    slug: 'professional_association',
    name: 'Professional Association',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['PA', 'P.A.'],
    summary: 'A professional entity form used in selected states.',
    ownership: 'Often restricted to licensed professionals.',
    liability: 'Limited liability for business obligations, not personal malpractice.',
    taxation: 'Usually corporate or S corporation taxation depending on election.',
    management: 'Professional owners/directors/officers as required by state law.',
    formation: 'State-specific professional filing.',
    bestFor: ['Professional practices in states using PA forms'],
    cautions: ['Availability and meaning vary by state'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['professional_corporation', 'professional_limited_liability_company'],
  },
  {
    slug: 'benefit_corporation',
    name: 'Benefit Corporation',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['public benefit corporation', 'PBC', 'benefit corp'],
    summary: 'A corporation with legally recognized public benefit obligations.',
    ownership: 'Shareholders.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Corporate taxation unless S election is available and made.',
    management:
      'Directors must consider stated benefit purposes and stakeholder interests as required by law.',
    formation: 'State benefit corporation filing or election where available.',
    bestFor: ['Mission-driven companies', 'Companies balancing profit and social purpose'],
    cautions: ['Not the same as B Lab certification', 'Benefit reporting may apply'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['public_benefit_llc', 'low_profit_limited_liability_company'],
  },
  {
    slug: 'close_corporation',
    name: 'Close Corporation',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['closely held corporation', 'closely held company'],
    summary: 'A corporation with a small number of shareholders and no public market for shares.',
    ownership: 'Small shareholder group.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Corporate taxation unless S election is available and made.',
    management: 'May operate with simplified governance depending on law and agreements.',
    formation: 'Can be factual or a statutory election depending on state.',
    bestFor: ['Family companies', 'Small private companies'],
    cautions: ['Transfer restrictions and shareholder disputes need planning'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['statutory_close_corporation', 'private_corporation'],
  },
  {
    slug: 'statutory_close_corporation',
    name: 'Statutory Close Corporation',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['statutory close corp'],
    summary: 'A state-law close corporation status with special governance rules.',
    ownership: 'Limited shareholder group under state rules.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Corporate taxation unless S election is available and made.',
    management: 'May allow shareholder management and reduced board formalities.',
    formation: 'Requires state-law election where available.',
    bestFor: ['Family businesses', 'Small closely held corporations'],
    cautions: ['State-specific restrictions apply'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['close_corporation'],
  },
  {
    slug: 'public_corporation',
    name: 'Public Corporation',
    category: 'regulatory_status',
    family: 'corporation',
    aliases: ['public company', 'publicly traded company', 'listed company'],
    summary: 'A corporation whose securities are publicly traded or publicly reporting.',
    ownership: 'Public shareholders.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Usually C corporation taxation in the U.S.',
    management: 'Board, officers, securities-law governance, and public reporting controls.',
    formation:
      'Starts as a corporation, then becomes public through securities registration/listing or similar process.',
    bestFor: ['Large capital raising', 'Public markets'],
    cautions: ['Heavy securities regulation and reporting obligations'],
    relatedStructures: ['corporation', 'c_corporation'],
  },
  {
    slug: 'private_corporation',
    name: 'Private Corporation',
    category: 'regulatory_status',
    family: 'corporation',
    aliases: ['privately held corporation', 'private company'],
    summary: 'A corporation not publicly traded.',
    ownership: 'Private shareholders.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Corporate or S corporation taxation depending on eligibility/election.',
    management: 'Board and officers.',
    formation: 'State corporate filing.',
    bestFor: ['Closely held businesses', 'Startups before public markets'],
    cautions: ['Share transfer and investor rights should be documented'],
    taxElectionOptions: ['c_corporation_taxation', 's_corporation_taxation'],
    relatedStructures: ['corporation', 'close_corporation'],
  },
  {
    slug: 'holding_company',
    name: 'Holding Company',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['holdco', 'parent company'],
    summary:
      'A company formed mainly to own subsidiaries, assets, intellectual property, or investments.',
    ownership: 'Depends on underlying entity.',
    liability: 'Depends on underlying entity and separateness from subsidiaries.',
    taxation: 'Depends on underlying entity and structure.',
    management: 'Depends on underlying entity.',
    formation: 'Usually formed as an LLC or corporation.',
    bestFor: ['Owning subsidiaries', 'Asset segregation', 'IP ownership', 'Real estate holdings'],
    cautions: ['Must preserve separateness and avoid commingling'],
    relatedStructures: ['limited_liability_company', 'corporation'],
  },
  {
    slug: 'joint_venture',
    name: 'Joint Venture',
    category: 'legal_entity',
    family: 'joint_venture',
    aliases: ['JV'],
    summary: 'A collaboration for a specific project or business purpose.',
    ownership: 'Two or more participants.',
    liability: 'Depends on whether contractual or formed through an entity.',
    taxation: 'Depends on structure; often partnership-like if not separately incorporated.',
    management: 'Defined by joint venture agreement or entity documents.',
    formation: 'Can be contractual or organized as an LLC, corporation, or partnership.',
    bestFor: ['Construction projects', 'Strategic partnerships', 'International expansion'],
    cautions: ['Scope, control, IP, exit, and liability must be clearly documented'],
    relatedStructures: ['limited_liability_company', 'general_partnership', 'corporation'],
  },
  {
    slug: 'joint_stock_company',
    name: 'Joint Stock Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['JSC'],
    summary:
      'A share-based company form used in many jurisdictions, similar in concept to a corporation.',
    ownership: 'Shareholders.',
    liability: 'Usually limited to share investment, depending on jurisdiction.',
    taxation: 'Country-specific corporate taxation.',
    management: 'Directors/officers or equivalent governance bodies.',
    formation: 'Country-specific company registration.',
    bestFor: ['Share-based enterprises outside the U.S.', 'Larger operating companies'],
    cautions: ['Meaning varies substantially by country'],
    countries: ['International'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'cooperative',
    name: 'Cooperative',
    category: 'legal_entity',
    family: 'cooperative',
    aliases: ['co-op', 'coop'],
    summary: 'An entity owned and governed by members who use or benefit from it.',
    ownership: 'Members such as workers, consumers, producers, residents, or customers.',
    liability: 'Depends on cooperative statute and entity form.',
    taxation: 'Special cooperative tax rules may apply.',
    management: 'Democratic or member-based governance.',
    formation: 'State cooperative filing or corporation/cooperative election.',
    bestFor: [
      'Worker-owned businesses',
      'Agricultural groups',
      'Retail co-ops',
      'Housing co-ops',
      'Electric co-ops',
    ],
    cautions: ['Governance and patronage rules are specialized'],
    variants: [
      'worker_cooperative',
      'consumer_cooperative',
      'producer_cooperative',
      'purchasing_cooperative',
      'housing_cooperative',
      'electric_cooperative',
      'credit_union',
    ],
    relatedStructures: ['nonprofit_corporation', 'corporation'],
  },
  {
    slug: 'worker_cooperative',
    name: 'Worker Cooperative',
    category: 'special_designation',
    family: 'cooperative',
    aliases: ['employee cooperative'],
    summary: 'A cooperative owned and governed by workers.',
    ownership: 'Worker-members.',
    liability: 'Depends on cooperative statute and entity form.',
    taxation: 'Cooperative or corporate rules depending on structure.',
    management: 'Member democratic governance.',
    formation: 'State cooperative filing or cooperative corporation structure.',
    bestFor: ['Employee-owned operating businesses'],
    cautions: ['Requires careful governance and patronage rules'],
    relatedStructures: ['cooperative', 'employee_stock_ownership_plan_company'],
  },
  {
    slug: 'credit_union',
    name: 'Credit Union',
    category: 'regulatory_status',
    family: 'cooperative',
    aliases: ['federal credit union', 'state credit union'],
    summary: 'A member-owned financial cooperative.',
    ownership: 'Members/depositors.',
    liability: 'Special financial institution rules apply.',
    taxation: 'Special credit union tax and regulatory treatment.',
    management: 'Board and regulated financial institution governance.',
    formation: 'Requires federal or state credit union charter.',
    bestFor: ['Member-owned financial services'],
    cautions: ['Heavily regulated; cannot be formed like an ordinary business'],
    relatedStructures: ['cooperative', 'bank_regulated_entity'],
  },
  {
    slug: 'mutual_company',
    name: 'Mutual Company',
    category: 'legal_entity',
    family: 'cooperative',
    aliases: ['mutual insurance company', 'mutual benefit company'],
    summary: 'A company owned by policyholders, depositors, or customers rather than stockholders.',
    ownership: 'Members/policyholders/customers.',
    liability: 'Depends on governing statute and regulated industry.',
    taxation: 'Industry-specific taxation.',
    management: 'Board and member governance.',
    formation: 'Often requires specialized insurance or financial regulatory approval.',
    bestFor: ['Insurance', 'Financial services', 'Member-benefit organizations'],
    cautions: ['Usually regulated and not a general-purpose startup entity'],
    relatedStructures: ['cooperative', 'insurance_regulated_entity'],
  },
  {
    slug: 'nonprofit_corporation',
    name: 'Nonprofit Corporation',
    category: 'legal_entity',
    family: 'nonprofit',
    aliases: ['non-profit corporation', 'not-for-profit corporation'],
    summary: 'A state-law corporation organized for nonprofit purposes and without owners.',
    ownership: 'No owners; may have members depending on structure.',
    liability:
      'Directors, officers, and members generally receive statutory protections subject to law.',
    taxation: 'Not automatically tax-exempt; may apply for federal/state exemptions.',
    management: 'Board of directors/trustees and officers.',
    formation: 'State nonprofit articles plus tax exemption filings if needed.',
    bestFor: [
      'Charities',
      'Foundations',
      'Religious organizations',
      'Trade associations',
      'Social welfare organizations',
    ],
    cautions: [
      'No private ownership of profits',
      'Tax-exempt status has restrictions and compliance obligations',
    ],
    variants: [
      'charitable_nonprofit',
      'religious_corporation',
      'membership_nonprofit',
      'mutual_benefit_nonprofit',
      'public_benefit_nonprofit',
      'foundation',
    ],
    taxElectionOptions: [
      '501c3_tax_exempt',
      '501c4_tax_exempt',
      '501c6_tax_exempt',
      'other_tax_exempt',
    ],
    relatedStructures: ['charitable_trust', 'unincorporated_association'],
  },
  {
    slug: 'charitable_nonprofit',
    name: 'Charitable Nonprofit',
    category: 'special_designation',
    family: 'nonprofit',
    aliases: ['charity', '501(c)(3) organization'],
    summary:
      'A nonprofit organized for charitable, educational, religious, scientific, or similar exempt purposes.',
    ownership: 'No owners.',
    liability: 'Usually organized through nonprofit corporation or trust protections.',
    taxation: 'Often seeks 501(c)(3) tax-exempt status.',
    management: 'Board governance.',
    formation: 'State nonprofit formation plus tax exemption application.',
    bestFor: ['Charities', 'Educational programs', 'Religious or scientific purposes'],
    cautions: ['Private benefit, lobbying, and political activity restrictions may apply'],
    taxElectionOptions: ['501c3_tax_exempt'],
    relatedStructures: ['nonprofit_corporation', 'charitable_trust', 'foundation'],
  },
  {
    slug: 'religious_corporation',
    name: 'Religious Corporation',
    category: 'special_designation',
    family: 'nonprofit',
    aliases: ['church corporation', 'religious nonprofit'],
    summary: 'A nonprofit or special corporation organized for religious purposes.',
    ownership: 'No owners; may have members/congregants.',
    liability: 'Depends on state nonprofit/religious corporation law.',
    taxation: 'May qualify for religious tax exemptions.',
    management: 'Board, trustees, elders, or other faith-governance model.',
    formation: 'State-specific nonprofit or religious corporation filing.',
    bestFor: ['Churches', 'Synagogues', 'Mosques', 'Temples', 'Religious ministries'],
    cautions: ['Governance and property rules may be state- and denomination-specific'],
    taxElectionOptions: ['501c3_tax_exempt'],
    relatedStructures: ['nonprofit_corporation'],
  },
  {
    slug: 'foundation',
    name: 'Foundation',
    category: 'special_designation',
    family: 'nonprofit',
    aliases: ['private foundation', 'community foundation', 'corporate foundation'],
    summary: 'A nonprofit or trust structure that funds charitable activities or grantmaking.',
    ownership: 'No owners.',
    liability: 'Depends on nonprofit corporation or trust form.',
    taxation: 'Often 501(c)(3), with private foundation or public charity classification.',
    management: 'Board or trustees.',
    formation: 'Usually nonprofit corporation or charitable trust plus tax exemption application.',
    bestFor: ['Grantmaking', 'Family philanthropy', 'Community funds', 'Corporate philanthropy'],
    cautions: ['Private foundation rules can be strict'],
    taxElectionOptions: ['501c3_tax_exempt'],
    relatedStructures: ['charitable_nonprofit', 'charitable_trust'],
  },
  {
    slug: 'unincorporated_association',
    name: 'Unincorporated Association',
    category: 'legal_entity',
    family: 'nonprofit',
    aliases: ['association', 'club'],
    summary: 'A group acting together without forming a separate corporation or LLC.',
    ownership: 'Members or participants.',
    liability: 'Liability protections vary and may be limited.',
    taxation: 'Depends on activity and tax filings; may seek exemption in some cases.',
    management: 'Member rules, bylaws, or informal governance.',
    formation: 'Often no entity filing, though tax, bank, DBA, and exemption filings may apply.',
    bestFor: ['Clubs', 'Volunteer groups', 'Small community groups'],
    cautions: ['Weak entity separateness and liability protection'],
    relatedStructures: ['nonprofit_corporation'],
  },
  {
    slug: 'business_trust',
    name: 'Business Trust',
    category: 'legal_entity',
    family: 'trust',
    aliases: ['common law business trust', 'Massachusetts trust'],
    summary: 'A trust arrangement used to operate a business or hold business assets.',
    ownership: 'Beneficiaries hold beneficial interests.',
    liability: 'Depends on trust law, documents, and jurisdiction.',
    taxation: 'Trust or business entity tax rules depending on classification.',
    management: 'Trustees manage for beneficiaries.',
    formation: 'Trust instrument; may require filings depending on jurisdiction/activity.',
    bestFor: ['Asset holding', 'Investment arrangements', 'Specialized legacy structures'],
    cautions: ['Complex legal and tax classification issues'],
    relatedStructures: ['statutory_trust'],
  },
  {
    slug: 'statutory_trust',
    name: 'Statutory Trust',
    category: 'legal_entity',
    family: 'trust',
    aliases: ['DST', 'Delaware statutory trust'],
    summary: 'A trust formed under a specific statutory trust law.',
    ownership: 'Beneficial owners.',
    liability: 'Statutory liability rules may protect beneficial owners and trustees.',
    taxation: 'Depends on classification and activity.',
    management: 'Trustees manage under governing instrument.',
    formation: 'State statutory trust filing where available.',
    bestFor: ['Investment funds', 'Real estate ownership', 'Securitization structures'],
    cautions: ['Specialized and jurisdiction-specific'],
    relatedStructures: ['business_trust', 'real_estate_investment_trust'],
  },
  {
    slug: 'charitable_trust',
    name: 'Charitable Trust',
    category: 'legal_entity',
    family: 'trust',
    aliases: ['charity trust'],
    summary: 'A trust organized to hold and use assets for charitable purposes.',
    ownership: 'No private owners; trustees hold assets for charitable purposes.',
    liability: 'Trust law applies.',
    taxation: 'May qualify for charitable tax treatment.',
    management: 'Trustees.',
    formation: 'Trust instrument plus charitable/tax filings as applicable.',
    bestFor: ['Charitable assets', 'Grantmaking', 'Legacy philanthropy'],
    cautions: ['Trustee duties and charitable restrictions apply'],
    taxElectionOptions: ['501c3_tax_exempt'],
    relatedStructures: ['foundation', 'nonprofit_corporation'],
  },
  {
    slug: 'real_estate_investment_trust',
    name: 'Real Estate Investment Trust',
    category: 'special_designation',
    family: 'trust',
    aliases: ['REIT'],
    summary: 'A real-estate investment vehicle with special federal tax requirements.',
    ownership: 'Shareholders or beneficial owners.',
    liability: 'Depends on underlying legal form.',
    taxation: 'Special REIT tax regime if federal requirements are met.',
    management: 'Trust/corporate management depending on form.',
    formation:
      'Typically organized as a corporation, trust, or association that elects REIT treatment.',
    bestFor: ['Income-producing real estate portfolios'],
    cautions: ['Strict asset, income, shareholder, and distribution tests'],
    relatedStructures: ['statutory_trust', 'corporation'],
  },
  {
    slug: 'employee_stock_ownership_plan_company',
    name: 'ESOP Company',
    category: 'special_designation',
    family: 'corporation',
    aliases: ['employee stock ownership plan company', 'employee-owned company'],
    summary: 'A company owned partly or fully through an employee stock ownership plan.',
    ownership: 'Employees beneficially own shares through a qualified retirement plan.',
    liability: 'Depends on underlying entity.',
    taxation: 'Special ESOP and retirement plan tax rules.',
    management: 'Company governance plus ESOP trustee/plan administration.',
    formation: 'Requires underlying company and qualified ESOP plan.',
    bestFor: ['Business succession', 'Employee ownership transitions'],
    cautions: ['Complex ERISA, valuation, and fiduciary rules'],
    relatedStructures: ['corporation', 'worker_cooperative'],
  },
  {
    slug: 'tribal_enterprise',
    name: 'Tribal Enterprise',
    category: 'regulatory_status',
    family: 'government',
    aliases: ['tribally owned business', 'tribal corporation'],
    summary: 'An enterprise owned by a federally recognized tribe or tribal instrumentality.',
    ownership: 'Tribe or tribal instrumentality.',
    liability: 'May involve sovereign immunity and tribal law.',
    taxation: 'Special federal, state, and tribal tax considerations.',
    management: 'Tribal governance or enterprise board.',
    formation: 'Tribal law, federal law, or state entity depending on structure.',
    bestFor: ['Tribal economic development', 'Government-owned enterprise activity'],
    cautions: ['Sovereignty, waiver, tax, and jurisdiction issues require specialized counsel'],
    relatedStructures: ['government_corporation'],
  },
  {
    slug: 'government_corporation',
    name: 'Government Corporation',
    category: 'legal_entity',
    family: 'government',
    aliases: ['public authority', 'state-owned enterprise', 'government-owned corporation'],
    summary: 'A corporation or authority owned or controlled by a government.',
    ownership: 'Federal, state, local, tribal, or foreign government.',
    liability: 'Public law and enabling statute control liability.',
    taxation: 'Governmental or special statutory treatment.',
    management: 'Statutory board, officers, or public officials.',
    formation: 'Created by statute, charter, or public act.',
    bestFor: ['Public utilities', 'Public infrastructure', 'Government economic activity'],
    cautions: ['Not a regular private formation path'],
    relatedStructures: ['tribal_enterprise'],
  },
  {
    slug: 'bank_regulated_entity',
    name: 'Bank or Depository Institution',
    category: 'regulatory_status',
    family: 'corporation',
    aliases: ['bank', 'national bank', 'state bank', 'savings bank', 'trust company'],
    summary: 'A regulated financial institution chartered by federal or state banking authorities.',
    ownership: 'Shareholders or mutual owners depending on charter.',
    liability: 'Regulated entity liability and capital rules apply.',
    taxation: 'Financial institution tax rules.',
    management: 'Board/officers plus banking regulatory oversight.',
    formation: 'Requires bank charter and regulatory approval.',
    bestFor: ['Depository and banking activities'],
    cautions: ['Cannot be formed by ordinary entity filing alone'],
    relatedStructures: ['corporation', 'mutual_company', 'credit_union'],
  },
  {
    slug: 'insurance_regulated_entity',
    name: 'Insurance Company',
    category: 'regulatory_status',
    family: 'corporation',
    aliases: ['insurer', 'insurance carrier', 'reinsurance company'],
    summary: 'A regulated entity authorized to write insurance or reinsurance.',
    ownership: 'Shareholders, mutual members, or policyholders depending on form.',
    liability: 'Insurance regulatory capital and solvency rules apply.',
    taxation: 'Insurance company tax rules.',
    management: 'Board/officers plus insurance department oversight.',
    formation: 'Requires certificate of authority or insurance regulatory approval.',
    bestFor: ['Insurance underwriting', 'Reinsurance'],
    cautions: ['Cannot be formed by ordinary entity filing alone'],
    relatedStructures: ['corporation', 'mutual_company'],
  },
  {
    slug: 'sole_proprietor_taxation',
    name: 'Sole Proprietor Taxation',
    category: 'tax_election',
    family: 'sole_proprietorship',
    aliases: ['Schedule C taxation'],
    summary: 'Tax treatment for an individual owner reporting business income directly.',
    ownership: 'One individual owner.',
    liability: 'Tax classification does not create liability protection.',
    taxation: 'Owner reports income directly.',
    management: 'N/A tax classification.',
    formation: 'Tax treatment, not a legal entity filing.',
    bestFor: ['Sole proprietors', 'Single-member LLCs taxed as disregarded entities'],
    cautions: ['Not a legal entity type'],
    relatedStructures: ['sole_proprietorship', 'single_member_llc'],
  },
  {
    slug: 'disregarded_entity',
    name: 'Disregarded Entity',
    category: 'tax_election',
    family: 'llc',
    aliases: ['DRE', 'single member disregarded entity'],
    summary: 'Federal tax treatment where an entity is ignored as separate from its owner.',
    ownership: 'Single owner.',
    liability: 'Tax classification does not determine legal liability.',
    taxation: 'Income is reported by the owner.',
    management: 'N/A tax classification.',
    formation: 'Tax classification, commonly default for single-member LLCs.',
    bestFor: ['Single-member LLCs'],
    cautions: ['Not a legal entity type'],
    relatedStructures: ['single_member_llc'],
  },
  {
    slug: 'partnership_taxation',
    name: 'Partnership Taxation',
    category: 'tax_election',
    family: 'partnership',
    aliases: ['pass-through partnership taxation'],
    summary: 'Pass-through federal tax treatment for partnerships and many multi-member LLCs.',
    ownership: 'Two or more owners for tax purposes.',
    liability: 'Tax classification does not determine legal liability.',
    taxation: 'Entity files partnership return; income/loss passes to owners.',
    management: 'N/A tax classification.',
    formation: 'Tax classification, not a legal entity type.',
    bestFor: ['Partnerships', 'Multi-member LLCs'],
    cautions: ['Allocations and basis rules can be complex'],
    relatedStructures: ['general_partnership', 'multi_member_llc', 'limited_partnership'],
  },
  {
    slug: 'c_corporation_taxation',
    name: 'C Corporation Taxation',
    category: 'tax_election',
    family: 'corporation',
    aliases: ['corporate taxation', 'Subchapter C'],
    summary: 'Federal corporate income tax treatment.',
    ownership: 'Shareholders or members depending on underlying entity.',
    liability: 'Tax classification does not determine legal liability.',
    taxation: 'Entity-level tax; dividends may be taxed to owners.',
    management: 'N/A tax classification.',
    formation: 'Default for corporations; elective for some LLCs.',
    bestFor: ['Venture-backed companies', 'Multiple stock classes', 'Reinvestment of profits'],
    cautions: ['Possible double taxation'],
    relatedStructures: ['corporation', 'limited_liability_company'],
  },
  {
    slug: 's_corporation_taxation',
    name: 'S Corporation Taxation',
    category: 'tax_election',
    family: 'corporation',
    aliases: ['Subchapter S taxation'],
    summary: 'Pass-through tax election for eligible corporations and LLCs.',
    ownership: 'Restricted owner types and shareholder count.',
    liability: 'Tax classification does not determine legal liability.',
    taxation: 'Pass-through taxation with S corporation rules.',
    management: 'N/A tax classification.',
    formation: 'Tax election filed with tax authority.',
    bestFor: ['Eligible owner-operated businesses'],
    cautions: ['Eligibility and payroll rules matter'],
    relatedStructures: ['s_corporation', 'corporation', 'limited_liability_company'],
  },
  {
    slug: '501c3_tax_exempt',
    name: '501(c)(3) Tax-Exempt Status',
    category: 'tax_election',
    family: 'nonprofit',
    aliases: ['501c3', 'public charity status', 'private foundation status'],
    summary:
      'Federal tax-exempt status for charitable, religious, educational, scientific, and similar organizations.',
    ownership: 'No private owners.',
    liability: 'Tax status does not determine state-law liability.',
    taxation:
      'Exempt from federal income tax on related exempt-purpose income; donations may be deductible.',
    management: 'Board governance and exemption compliance.',
    formation: 'Tax exemption application or qualification after entity formation.',
    bestFor: ['Charities', 'Schools', 'Religious organizations', 'Foundations'],
    cautions: ['Private benefit, lobbying, and political restrictions'],
    relatedStructures: ['nonprofit_corporation', 'charitable_trust', 'foundation'],
  },
  {
    slug: '501c4_tax_exempt',
    name: '501(c)(4) Tax-Exempt Status',
    category: 'tax_election',
    family: 'nonprofit',
    aliases: ['social welfare organization'],
    summary: 'Federal tax-exempt status for social welfare organizations.',
    ownership: 'No private owners.',
    liability: 'Tax status does not determine state-law liability.',
    taxation: 'Tax-exempt treatment for qualifying social welfare activity.',
    management: 'Board governance and exemption compliance.',
    formation: 'Tax exemption filing after entity formation.',
    bestFor: ['Advocacy and social welfare organizations'],
    cautions: ['Donation deductibility and political activity rules differ from 501(c)(3)'],
    relatedStructures: ['nonprofit_corporation'],
  },
  {
    slug: '501c6_tax_exempt',
    name: '501(c)(6) Tax-Exempt Status',
    category: 'tax_election',
    family: 'nonprofit',
    aliases: ['business league', 'trade association', 'chamber of commerce'],
    summary:
      'Federal tax-exempt status for business leagues, chambers, boards of trade, and similar groups.',
    ownership: 'No private owners.',
    liability: 'Tax status does not determine state-law liability.',
    taxation: 'Tax-exempt treatment for qualifying trade association activity.',
    management: 'Board or member governance.',
    formation: 'Tax exemption filing after entity formation.',
    bestFor: ['Trade associations', 'Chambers of commerce', 'Professional associations'],
    cautions: ['Must promote common business interests rather than operate for profit'],
    relatedStructures: ['nonprofit_corporation'],
  },
  {
    slug: 'licensed_professional_status',
    name: 'Licensed Professional Status',
    category: 'regulatory_status',
    family: 'llc',
    aliases: ['professional services restriction', 'licensed profession'],
    summary: 'A regulatory overlay for businesses offering licensed professional services.',
    ownership: 'Often restricted to licensed individuals or entities.',
    liability: 'Entity shield may not cover personal malpractice.',
    taxation: 'Depends on underlying entity.',
    management: 'May require licensed professional control.',
    formation: 'May require licensing board approval or special entity form.',
    bestFor: ['Doctors', 'Lawyers', 'Accountants', 'Architects', 'Engineers', 'Dentists'],
    cautions: ['State and licensing board rules control'],
    relatedStructures: [
      'professional_limited_liability_company',
      'professional_corporation',
      'limited_liability_partnership',
    ],
  },
  {
    slug: 'certified_b_corporation',
    name: 'Certified B Corporation',
    category: 'regulatory_status',
    family: 'corporation',
    aliases: ['B Corp certification'],
    summary: 'A private certification from B Lab, not a legal entity type.',
    ownership: 'Depends on underlying entity.',
    liability: 'Depends on underlying entity.',
    taxation: 'Depends on underlying entity.',
    management: 'Depends on underlying entity and certification commitments.',
    formation: 'Certification process, not state entity formation.',
    bestFor: ['Mission-driven companies seeking third-party certification'],
    cautions: ['Different from legal Benefit Corporation status'],
    relatedStructures: ['benefit_corporation', 'public_benefit_llc'],
  },
  {
    slug: 'canada_corporation',
    name: 'Canada Corporation',
    category: 'international_entity',
    family: 'international',
    aliases: ['Canadian corporation', 'federal corporation', 'provincial corporation'],
    summary: 'Canadian share corporation formed federally or provincially.',
    ownership: 'Shareholders.',
    liability: 'Shareholders generally receive limited liability.',
    taxation: 'Canadian corporate taxation.',
    management: 'Directors and officers.',
    formation: 'Federal or provincial incorporation.',
    bestFor: ['Canadian operating companies'],
    cautions: ['Federal/provincial and residency rules vary'],
    countries: ['Canada'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'canada_unlimited_liability_company',
    name: 'Canada Unlimited Liability Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['ULC', 'unlimited liability company'],
    summary:
      'A Canadian company form with shareholder liability features used in specialized planning.',
    ownership: 'Shareholders.',
    liability: 'Shareholders may have unlimited liability under applicable provincial law.',
    taxation: 'Canadian and cross-border tax rules can be complex.',
    management: 'Directors and officers.',
    formation: 'Available in selected provinces.',
    bestFor: ['Specialized cross-border structures'],
    cautions: ['Requires specialized legal and tax advice'],
    countries: ['Canada'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'uk_limited_company',
    name: 'UK Private Limited Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['Ltd', 'private company limited by shares'],
    summary: 'A UK private company with limited shareholder liability.',
    ownership: 'Shareholders.',
    liability: 'Shareholders generally limited to unpaid share amounts.',
    taxation: 'UK corporation tax.',
    management: 'Directors; company secretary may be used.',
    formation: 'Companies House incorporation.',
    bestFor: ['UK private businesses'],
    cautions: ['UK filing and persons-with-significant-control rules apply'],
    countries: ['United Kingdom'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'uk_public_limited_company',
    name: 'UK Public Limited Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['PLC', 'public limited company'],
    summary:
      'A UK public company form capable of offering shares to the public if requirements are met.',
    ownership: 'Shareholders.',
    liability: 'Shareholders generally limited to unpaid share amounts.',
    taxation: 'UK corporation tax.',
    management: 'Directors and public company governance.',
    formation: 'Companies House incorporation and PLC requirements.',
    bestFor: ['Larger UK companies', 'Public capital markets'],
    cautions: ['Higher capital and governance requirements'],
    countries: ['United Kingdom'],
    relatedStructures: ['public_corporation'],
  },
  {
    slug: 'uk_company_limited_by_guarantee',
    name: 'UK Company Limited by Guarantee',
    category: 'international_entity',
    family: 'international',
    aliases: ['CLG', 'guarantee company'],
    summary: 'A UK company without share capital, commonly used for nonprofits and clubs.',
    ownership: 'Members guarantee a nominal amount.',
    liability: 'Members liability limited to guarantee amount.',
    taxation: 'UK tax treatment depends on activities and charity status.',
    management: 'Directors and members.',
    formation: 'Companies House incorporation.',
    bestFor: ['Charities', 'Clubs', 'Associations'],
    cautions: ['Not designed for equity investment'],
    countries: ['United Kingdom'],
    relatedStructures: ['nonprofit_corporation', 'unincorporated_association'],
  },
  {
    slug: 'uk_community_interest_company',
    name: 'UK Community Interest Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['CIC'],
    summary: 'A UK company form for social enterprises with community benefit obligations.',
    ownership: 'Shareholders or members depending on limited by shares/guarantee form.',
    liability: 'Limited liability.',
    taxation: 'UK corporation tax unless exemptions apply.',
    management: 'Directors with CIC regulator obligations.',
    formation: 'Companies House plus CIC regulator approval.',
    bestFor: ['UK social enterprises'],
    cautions: ['Asset lock and community interest test apply'],
    countries: ['United Kingdom'],
    relatedStructures: ['benefit_corporation'],
  },
  {
    slug: 'germany_gmbh',
    name: 'Germany GmbH',
    category: 'international_entity',
    family: 'international',
    aliases: ['Gesellschaft mit beschrankter Haftung'],
    summary: 'German limited liability company.',
    ownership: 'Shareholders.',
    liability: 'Generally limited liability.',
    taxation: 'German corporate and trade tax.',
    management: 'Managing directors.',
    formation: 'German notarial and commercial register process.',
    bestFor: ['German private companies'],
    cautions: ['Capital and notarial requirements apply'],
    countries: ['Germany'],
    relatedStructures: ['limited_liability_company', 'corporation'],
  },
  {
    slug: 'germany_ug',
    name: 'Germany UG',
    category: 'international_entity',
    family: 'international',
    aliases: ['UG haftungsbeschrankt', 'entrepreneurial company'],
    summary: 'German low-capital limited liability company variant.',
    ownership: 'Shareholders.',
    liability: 'Generally limited liability.',
    taxation: 'German corporate and trade tax.',
    management: 'Managing directors.',
    formation: 'German registration with lower initial capital than GmbH.',
    bestFor: ['Small German startups needing limited liability'],
    cautions: ['Profit reserve requirements apply until capital threshold is built'],
    countries: ['Germany'],
    relatedStructures: ['germany_gmbh'],
  },
  {
    slug: 'germany_ag',
    name: 'Germany AG',
    category: 'international_entity',
    family: 'international',
    aliases: ['Aktiengesellschaft'],
    summary: 'German stock corporation.',
    ownership: 'Shareholders.',
    liability: 'Generally limited liability.',
    taxation: 'German corporate and trade tax.',
    management: 'Management board and supervisory board.',
    formation: 'German stock corporation formation and register process.',
    bestFor: ['Larger German companies', 'Public markets'],
    cautions: ['Higher governance and capital requirements'],
    countries: ['Germany'],
    relatedStructures: ['public_corporation'],
  },
  {
    slug: 'france_sarl',
    name: 'France SARL',
    category: 'international_entity',
    family: 'international',
    aliases: ['societe a responsabilite limitee'],
    summary: 'French private limited liability company.',
    ownership: 'Associates/quotaholders.',
    liability: 'Generally limited to contributions.',
    taxation: 'French corporate tax by default, with options in some cases.',
    management: 'Gerant/manager.',
    formation: 'French company registration.',
    bestFor: ['French small and medium private companies'],
    cautions: ['French corporate formalities apply'],
    countries: ['France'],
    relatedStructures: ['limited_liability_company'],
  },
  {
    slug: 'france_sas',
    name: 'France SAS',
    category: 'international_entity',
    family: 'international',
    aliases: ['societe par actions simplifiee'],
    summary: 'Flexible French simplified joint-stock company.',
    ownership: 'Shareholders.',
    liability: 'Generally limited to contributions.',
    taxation: 'French corporate tax by default.',
    management: 'President and governance set by bylaws.',
    formation: 'French company registration.',
    bestFor: ['French startups', 'Flexible governance', 'Investment-backed companies'],
    cautions: ['Bylaws need careful drafting'],
    countries: ['France'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'france_sasu',
    name: 'France SASU',
    category: 'international_entity',
    family: 'international',
    aliases: ['single-shareholder SAS'],
    summary: 'Single-shareholder version of the French SAS.',
    ownership: 'One shareholder.',
    liability: 'Generally limited to contributions.',
    taxation: 'French corporate tax by default.',
    management: 'President.',
    formation: 'French company registration.',
    bestFor: ['Solo French founders wanting a company form'],
    cautions: ['French payroll/social rules may matter for owner-managers'],
    countries: ['France'],
    relatedStructures: ['france_sas', 'single_member_llc'],
  },
  {
    slug: 'australia_pty_ltd',
    name: 'Australia Proprietary Limited Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['Pty Ltd', 'proprietary company'],
    summary: 'Australian private company limited by shares.',
    ownership: 'Shareholders.',
    liability: 'Generally limited liability.',
    taxation: 'Australian company tax.',
    management: 'Directors.',
    formation: 'ASIC registration.',
    bestFor: ['Australian private businesses'],
    cautions: ['ASIC and director obligations apply'],
    countries: ['Australia'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'australia_incorporated_association',
    name: 'Australia Incorporated Association',
    category: 'international_entity',
    family: 'international',
    aliases: ['incorporated association'],
    summary: 'Australian incorporated nonprofit association, generally state/territory based.',
    ownership: 'Members.',
    liability: 'Separate legal entity with limited member liability.',
    taxation: 'Depends on nonprofit and tax status.',
    management: 'Committee/board.',
    formation: 'State or territory incorporation.',
    bestFor: ['Clubs', 'Community groups', 'Nonprofits'],
    cautions: ['State/territory rules vary'],
    countries: ['Australia'],
    relatedStructures: ['nonprofit_corporation', 'unincorporated_association'],
  },
  {
    slug: 'india_private_limited_company',
    name: 'India Private Limited Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['Pvt Ltd', 'private limited company'],
    summary: 'Indian private company limited by shares.',
    ownership: 'Shareholders.',
    liability: 'Generally limited liability.',
    taxation: 'Indian corporate taxation.',
    management: 'Directors.',
    formation: 'MCA incorporation.',
    bestFor: ['Indian startups', 'Private operating companies'],
    cautions: ['Indian Companies Act compliance applies'],
    countries: ['India'],
    relatedStructures: ['corporation'],
  },
  {
    slug: 'india_one_person_company',
    name: 'India One Person Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['OPC'],
    summary: 'Indian company form for a single owner.',
    ownership: 'One member/shareholder with nominee requirements.',
    liability: 'Generally limited liability.',
    taxation: 'Indian corporate taxation.',
    management: 'Director governance under Indian company law.',
    formation: 'MCA incorporation.',
    bestFor: ['Solo Indian founders wanting a company form'],
    cautions: ['Eligibility and conversion rules apply'],
    countries: ['India'],
    relatedStructures: ['single_member_llc', 'corporation'],
  },
  {
    slug: 'india_llp',
    name: 'India Limited Liability Partnership',
    category: 'international_entity',
    family: 'international',
    aliases: ['Indian LLP'],
    summary: 'Indian partnership entity with limited liability.',
    ownership: 'Partners/designated partners.',
    liability: 'Limited liability subject to law.',
    taxation: 'Indian LLP taxation.',
    management: 'Partners/designated partners.',
    formation: 'MCA LLP registration.',
    bestFor: ['Professional and closely held Indian businesses'],
    cautions: ['Partner/designated partner compliance applies'],
    countries: ['India'],
    relatedStructures: ['limited_liability_partnership'],
  },
  {
    slug: 'india_section_8_company',
    name: 'India Section 8 Company',
    category: 'international_entity',
    family: 'international',
    aliases: ['Section 8 nonprofit company'],
    summary: 'Indian nonprofit company for charitable or similar objects.',
    ownership: 'Members, no profit distribution.',
    liability: 'Limited by shares or guarantee depending on form.',
    taxation: 'Indian nonprofit/tax exemption rules may apply.',
    management: 'Directors.',
    formation: 'MCA Section 8 license and incorporation.',
    bestFor: ['Indian nonprofits', 'Charitable companies'],
    cautions: ['Restrictions on profit distribution and object changes'],
    countries: ['India'],
    relatedStructures: ['nonprofit_corporation'],
  },
];

const bySlug = new Map(BUSINESS_STRUCTURES.map((structure) => [structure.slug, structure]));

export function listBusinessStructures(
  filters: {
    category?: BusinessStructureCategory;
    family?: BusinessStructureFamily;
    country?: string;
    q?: string;
  } = {},
) {
  const q = filters.q?.trim().toLowerCase();
  const country = filters.country?.trim().toLowerCase();
  return BUSINESS_STRUCTURES.filter((structure) => {
    if (filters.category && structure.category !== filters.category) return false;
    if (filters.family && structure.family !== filters.family) return false;
    if (
      country &&
      !(structure.countries ?? ['United States']).some((item) => item.toLowerCase() === country)
    ) {
      return false;
    }
    if (!q) return true;
    const haystack = [
      structure.slug,
      structure.name,
      structure.category,
      structure.family,
      structure.summary,
      ...structure.aliases,
      ...(structure.variants ?? []),
      ...(structure.bestFor ?? []),
    ]
      .join(' ')
      .toLowerCase();
    return haystack.includes(q);
  });
}

export function getBusinessStructure(slug: string) {
  return bySlug.get(slug);
}

export function recommendBusinessStructures(input: BusinessStructureRecommendationInput) {
  const reasons: Array<{ slug: string; score: number; reasons: string[] }> = [];
  const add = (slug: string, score: number, reason: string) => {
    const existing = reasons.find((item) => item.slug === slug);
    if (existing) {
      existing.score += score;
      existing.reasons.push(reason);
    } else {
      reasons.push({ slug, score, reasons: [reason] });
    }
  };

  if (
    input.country &&
    !['us', 'usa', 'united states', 'united states of america'].includes(
      input.country.toLowerCase(),
    )
  ) {
    for (const structure of listBusinessStructures({ country: input.country })) {
      add(structure.slug, 20, `Matches ${input.country} formation context.`);
    }
  }

  if (input.nonprofit || input.charitablePurpose) {
    add(
      'nonprofit_corporation',
      40,
      'Nonprofit or charitable purpose points to a nonprofit legal entity.',
    );
    add('charitable_nonprofit', 25, 'Charitable work may fit a charitable nonprofit.');
    add('foundation', 15, 'Grantmaking or asset-funded charity may fit a foundation.');
  }

  if (input.cooperativeOwnership) {
    add('cooperative', 35, 'Member ownership points to cooperative structures.');
    add('worker_cooperative', 20, 'Worker ownership may fit a worker cooperative.');
  }

  if (input.licensedProfessional) {
    add(
      'professional_limited_liability_company',
      35,
      'Licensed professional ownership may require a PLLC.',
    );
    add('professional_corporation', 30, 'Some states require or prefer professional corporations.');
    add('limited_liability_partnership', 15, 'Professional partnerships often use LLPs.');
  }

  if (input.ventureBacked || input.wantsStock) {
    add('corporation', 40, 'Stock issuance and venture financing usually point to a corporation.');
    add('c_corporation', 30, 'Venture-backed companies commonly use C corporation taxation.');
  }

  if (input.realEstateOrHoldings) {
    add('limited_liability_company', 25, 'LLCs are commonly used for real estate and holdings.');
    add('series_llc', 15, 'Multiple assets may fit a Series LLC where recognized.');
    add('holding_company', 15, 'Owning subsidiaries or assets may fit a holding company.');
    add('limited_partnership', 10, 'Real estate investment projects sometimes use LPs.');
  }

  if (input.wantsLiabilityProtection) {
    add('limited_liability_company', 35, 'Liability protection with flexibility points to an LLC.');
    add('corporation', 25, 'Corporations provide shareholder liability protection.');
  } else if (input.ownerCount === 1) {
    add(
      'sole_proprietorship',
      25,
      'One owner without liability protection can operate as a sole proprietorship.',
    );
  } else if ((input.ownerCount ?? 0) > 1) {
    add(
      'general_partnership',
      15,
      'Multiple owners without entity protection may form a general partnership.',
    );
  }

  if (input.ownerCount === 1 && input.wantsLiabilityProtection) {
    add(
      'single_member_llc',
      30,
      'One owner wanting liability protection often fits a single-member LLC.',
    );
  }

  if ((input.ownerCount ?? 0) > 1 && input.wantsLiabilityProtection && !input.wantsStock) {
    add(
      'multi_member_llc',
      25,
      'Multiple owners wanting flexible liability protection often fit a multi-member LLC.',
    );
  }

  if (reasons.length === 0) {
    add('limited_liability_company', 10, 'Default flexible structure for many small businesses.');
    add('corporation', 8, 'Default structure for stock-based companies.');
    add('sole_proprietorship', 5, 'Simple option for a single owner with low risk.');
  }

  return reasons
    .sort((a, b) => b.score - a.score)
    .slice(0, 8)
    .map((item) => ({
      score: item.score,
      reasons: item.reasons,
      structure: getBusinessStructure(item.slug),
    }));
}
